version: '3.8'

services:
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    command: sh -c "npm install && npm start" 
    user: "${UID:-1000}:${GID:-1000}"